### ISSUE TITLE
Linux + Case sensitivity: file references need update

### ISSUE THREAD

**Issue by cocoon** [rodriguezfa/AdminLTE.NETCore#1]
Hi.
Thanks for the work on the template.
I started today to get it running on Ubuntu 16.04.02 

First thing is easy, run:
```
dotnet migrate
dotnet restore
```

Then Linux is case sensitive regarding filenames and URLs.

I found already some problems like:

**File: Controllers/Dashboard.cs**

**WRONG:**
```csharp
 public IActionResult DashboardV1(bool partial = false)
...
 public IActionResult DashboardV2(bool partial = false)
```

**CORRECTED:**
```csharp
 public IActionResult Dashboardv1(bool partial = false)
...
 public IActionResult Dashboardv2(bool partial = false)
```

**WRONG:**
```csharp
./Controllers/DashboardController.cs:        [ScriptAfterPartialView("/lib/adminLTE-2.3.11/dist/js/pages/dashboard.min.js")]
./Controllers/DashboardController.cs:        [ScriptAfterPartialView("/lib/adminLTE-2.3.11/dist/js/pages/dashboard2.min.js")]
```

**CORRECTED:**
```csharp
./Controllers/DashboardController.cs:        [ScriptAfterPartialView("/lib/AdminLTE-2.3.11/dist/js/pages/dashboard.min.js")]
./Controllers/DashboardController.cs:        [ScriptAfterPartialView("/lib/AdminLTE-2.3.11/dist/js/pages/dashboard2.min.js")]
```

So far I can run it, but the middle area is still empty.

**Comment by cocoon** [comment]
OK the error I currently can see is:
`Error: Graph container element not found  morris.min.js:6:1340`

But I don't know how to fix that currently.

**Comment by rodriguezfa** [comment]
Hi.  The middle area is coming in as partial views.  The partial views are rendered from the source AdminLTE html pages.  I haven't look into this project in a while but will take a look and see why it doesn't work for you.
I have the sample running on the site mentioned on the page.  Some elements were not implemented, like the top menu, but most others are.
- Francisco

**Comment by rodriguezfa** [comment]
Please take a look at the Views\Dashboard\Dashboardv1.cshtml and see if there is an issue with case sensitive names like you found on other modules.
Also, you can test and see if it's an issue with partial view or not by rendering the entire page by accessing the component directly, ie https://frodriguez.xyz/Dashboard/dashboardv1  {site}/{controller}/{action}

**Comment by cocoon** [comment]
Wow I didn't expect such a quick reply, thanks!

- Accessing components direct doesn't change anything.
- Files on the Dashboard seem to be OK now, all are loaded with status 200 OK

- When clicking on "Photo Swipe" it does at least load the title, breadcrumb and empty white area.
There I currently found a 404:
`/js/photoswipe/photoswipe.min.js?_=1494862761417
404 Not Found`

~~Folder "js/PhotoSwipe" needs to be renamed to "js/photoswipe"~~

File: Controllers/PhotoSwipeController.cs
`/js/photoswipe/photoswipe.min.js --> /js/PhotoSwipe/photoswipe.min.js`

File: Controllers/FormsController.cs
2 x `/js/forms/  --> /js/Forms/`


File: Controllers/UiElementsController.cs
`public IActionResult Timeline(bool partial = false)`
to
`public IActionResult TimeLine(bool partial = false)`


File: Controllers/TablesController.cs
`js/tables/ --> js/Tables/`

File: Controllers/MailBoxController.cs
`public IActionResult Inbox(bool partial = false) --> public IActionResult InBox(bool partial = false)`

File: Controllers/ExamplesController.cs
`public IActionResult Lockscreen(bool partial = false) --> public IActionResult LockScreen(bool partial = false)`
and
`/js/examples/pace.min.js --> /js/Examples/pace.min.js`

Will check some more.

**Comment by cocoon** [comment]
Problem is, that there is only an empty response for the calls like:
Forms/GeneralElements?partial=true

but returns status 200 OK

**Comment by cocoon** [comment]
OK Progress, Dashboard is working.

Root cause is the use of (double) backslash in the Views-Files:

`wwwroot\\lib\\AdminLTE-2.3.11\\ --> wwwroot/lib/AdminLTE-2.3.11/`

**Comment by rodriguezfa** [comment]
Glad you are making progress!  This is a learning project and I have been working only on MS systems.  Sounds like most issues you are encountering are with case sensitive/os related items.  Great to learn about that!

**Comment by cocoon** [comment]
Yes, so here is how to make it work in both worlds, two examples, must be done for all files in Views of course:

**Dashboardv1**
`<html-extraction html-local-path="@System.IO.Path.Combine("wwwroot","lib","AdminLTE-2.3.11","index.html")"></html-extraction>`

**Dashboardv2**
`<html-extraction html-local-path="@System.IO.Path.Combine("wwwroot","lib","AdminLTE-2.3.11","index2.html")"></html-extraction>`

**Comment by rodriguezfa** [comment]
Do you mind updating the project so that these issues are addressed? 
Thanks
Francisco

**Comment by cocoon** [comment]
I sent you a PR with my changes.
And at least two pages are still not rendering:
Examples\Login
Examples\Register

But on both Windows and Linux.

**Comment by rodriguezfa** [comment]
Thanks for the updates.  I will take a look at the Examples when I get a chance.  My guess is that the html extraction is not working because the source pages are different.
